### ISSUE TITLE
send.gif missing

### ISSUE THREAD

**Issue by splitt3r** [jasonliehr/MyBB-GoMobile#4]
First i have to say that this plugin is awesome! But the send.gif in images/mobile is missing by default. 
![send](https://f.cloud.github.com/assets/1869584/295307/17083f1e-9479-11e2-8544-6b656f4a2bc4.gif)

**Comment by d4fseeker** [comment]
Note: quickfix is to copy it from the parent directory. 
I assume that loading it from images/mobile instead of images is the actual bug.
